### ISSUE TITLE
Logo for the Project

### ISSUE THREAD

**Issue by luzpaz** [grd/FreePDM#43]
Ideas?

**Comment by grd** [comment]
I think that I better put it inside the discussion group, since it is not any real issue. But to answer your question, the answer is that I have no idea...

**Comment by MisterMakerNL** [comment]
I am keeping my eye's on this great idea! 
If you need any icons, please let me know!
I also made this icon already .
But not sure if the f gets replaced by that naughty word.... :) 
![FreePDM](https://user-images.githubusercontent.com/29804962/184502811-446ac6d4-ca0c-468d-a012-493baad0804b.png)
