### ISSUE TITLE
PySide6

### ISSUE THREAD

**Issue by grd** [grd/FreePDM#72]
Since FreeCAD is about to use PySide6, I think that we should also update from PySide2 to PySide6. I don't think that it is that much work ;-)

Gerard

**Comment by luzpaz** [comment]
JFYI, here's the catch-all upstream FC ticket for Qt6 https://github.com/FreeCAD/FreeCAD/issues/6992

**Comment by grd** [comment]
This is now obsolete because I rewrote FreePDM in Go....
