### ISSUE TITLE
List building instructions

### ISSUE THREAD

**Issue by luzpaz** [grd/FreePDM#79]
List of dependencies etc...  in the README

**Comment by grd** [comment]
I agree. The document that was created a long time ago is obsolete.

**Comment by grd** [comment]
What do you prefer? That I should add things into the discussions group or into the Issues group? To me it doesn't really matter but I think that the discussions group is more separate from the real issues.

**Comment by grd** [comment]
Done. It is here: https://github.com/grd/FreePDM/blob/main/ConceptOfDesign/FreePDM_Install/README.md

**Comment by luzpaz** [comment]
Awesome!
