### ISSUE TITLE
Install docs: link to a fast way for multiple users to spin up a server

### ISSUE THREAD

**Issue by luzpaz** [grd/FreePDM#83]
> The specs for a file server are minimal (a RPI4/5 should work but is not tested yet). At this moment, I am using a desktop and it works for me. If there are multiple users, then consider using a proper server.

ref: https://github.com/grd/FreePDM/blob/main/ConceptOfDesign/FreePDM_Install/Install.md

Maybe we can add a link from 'consider using a proper server' to the tutorial that helps quickly spin up a server (on docker etc..)? Thoughts?

**Comment by grd** [comment]
Pff, I don't know. That is a hard question to answer. I have this document https://github.com/grd/FreePDM/blob/main/ConceptOfDesign/FreePDM_Install/Docker-Compose.md

Maybe I can advertise it better.

**Comment by luzpaz** [comment]
Yes, you can link to that 

Proposal: 
> The specs for a file server are minimal (a RPI4/5 should work but is not tested yet). At this moment, I am using a desktop and it works for me. If there are multiple users, then consider [using a proper server](https://github.com/grd/FreePDM/blob/main/ConceptOfDesign/FreePDM_Install/Docker-Compose.md).

**Comment by grd** [comment]
Okay. I thought that this was about writing specs and that would have been impossible. I am writing that right now.
